// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOM1Oi9N2sv1ReR3eG8zaJ4gKnur8kzZA',
    appId: '1:947095434440:web:1ce2d0ff91755fa37121fd',
    messagingSenderId: '947095434440',
    projectId: 'xamxam-livraison',
    authDomain: 'xamxam-livraison.firebaseapp.com',
    storageBucket: 'xamxam-livraison.firebasestorage.app',
    measurementId: 'G-BJ5CD48MER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDR8nSdCOdqFQ9vKUV3tYnZ4816nS_Wnk',
    appId: '1:947095434440:android:a0a44d161089c50f7121fd',
    messagingSenderId: '947095434440',
    projectId: 'xamxam-livraison',
    storageBucket: 'xamxam-livraison.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2iJb2OpvdHZDDi8T0CwVGWu6z9DEKr0',
    appId: '1:947095434440:ios:b097548c986fb5f27121fd',
    messagingSenderId: '947095434440',
    projectId: 'xamxam-livraison',
    storageBucket: 'xamxam-livraison.firebasestorage.app',
    iosBundleId: 'com.xoolibeut.livreur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2iJb2OpvdHZDDi8T0CwVGWu6z9DEKr0',
    appId: '1:947095434440:ios:17fb6f29ece484567121fd',
    messagingSenderId: '947095434440',
    projectId: 'xamxam-livraison',
    storageBucket: 'xamxam-livraison.firebasestorage.app',
    iosBundleId: 'com.example.flutterXoolibeutAddLieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOM1Oi9N2sv1ReR3eG8zaJ4gKnur8kzZA',
    appId: '1:947095434440:web:444322b7fb1421107121fd',
    messagingSenderId: '947095434440',
    projectId: 'xamxam-livraison',
    authDomain: 'xamxam-livraison.firebaseapp.com',
    storageBucket: 'xamxam-livraison.firebasestorage.app',
    measurementId: 'G-HH1HH044CF',
  );

}